version: "2"

services:
  blog-mysql:
    container_name: blog-mysql
    image: mysql:8.2.0
    ports:
      - 3306:3306
    volumes:
      - mysql-data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
    command: ['mysqld',
      '--character-set-server=utf8mb4',
      '--collation-server=utf8mb4_unicode_ci',
      '--default-authentication-plugin=mysql_native_password'
      ]
    networks:
      - blog-mysql
    restart: always

networks:
  blog-mysql:
    name: blog-mysql
    driver: bridge

volumes:
  mysql-data:
    external: true
