version: "2"

services:
  blog-mysql:
    container_name: blog-mysql
    image: mysql:5.7
    ports:
      - 3306:3306
    volumes:
      - blog-mysql-data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
    command: mysqld --sql_mode="NO_AUTO_VALUE_ON_ZERO,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION,PIPES_AS_CONCAT,ANSI_QUOTES"
    networks:
      - blog-mysql
    restart: always

networks:
  blog-mysql:
    name: blog-mysql
    driver: bridge

volumes:
  blog-mysql-data:
    name: blog-mysql-data
