version: '2'

services:
  db:
    container_name: clickhouse
    image: clickhouse/clickhouse-server
    ports:
     - 8123:8123
     - 9000:9000/tcp
    volumes:
      - /d/workspace/docker_share/clickhouse/:/var/lib/clickhouse/
    environment:
      - CLICKHOUSE_DB=devops
      - CLICKHOUSE_USER=devops
      - CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT=1
      - CLICKHOUSE_PASSWORD=devops123
    network_mode: bridge
    restart: always