apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
data:
  username: cm9vdA==
  password: MTIzNDU2

--- 
apiVersion: v1
kind: Secret
metadata:
  name: mysql-nacos-secret
data:
  # nacos_devtest
  database: bmFjb3NfZGV2dGVzdAo=
  username: bmFjb3MK
  password: bmFjb3MxMjMzCg==