version: '2'
services:
  nginx:
    restart: always
    image: nginx
    container_name: nginx
    volumes:
      - ./kuboard_proxy.conf:/etc/nginx/conf.d/default.conf:ro
      - ./pki/:/etc/nginx/pki:ro
    ports:
      - 80:80
      - 443:443

networks:
  nginx:
    name: nginx
    driver: bridge