version: '2'
services:
  nginx:
    restart: always
    image: nginx
    container_name: nginx
    volumes:
      - ./local_proxy.conf:/etc/nginx/conf.d/default.conf:ro
      - ./pki/:/etc/nginx/pki:ro
    ports:
      - 8888:8888
    networks:
      - nginx

networks:
  nginx:
    name: nginx
    driver: bridge