# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
  
    # Runs a single command using the runners shell
    - name: 修改bolg菜单
      run: |
        git config --global user.email "DoNobody@github.com"
        git config --global user.name "DoNobody"
        git checkout gh-pages
        git pull
        git merge master
        find . -mindepth 2 -name "*.md" | awk -F'/' 'BEGIN {RS=".md"} {k=$3;v=$2"/"$3"/"$4;if ($4=="README") {k=$3;v=$2"/"$3"/"} else if ($4=="") {k=$3;v=$2"/"$3} else k=$3"_"$4;arr[$2]=arr[$2]"\n  - ["k"]("v")"} END { num = asorti(arr, indices); for (i=1; i<=num; ++i) if (indices[i]) print "- "indices[i], arr[indices[i]]}' > _navbar.md
        sed 's/^-/---\n#/g' _navbar.md |sed 's/^  - \(\[\(\w*\)\]\w*\)/## \2\n  > \1/g' > README.md 
        find . -mindepth 2 -name "*.md"|xargs -i bash -c 'grep -Fq "[首页](/)" {}||sed -i "1 i\[首页](/)" {}'
        git add .
        git status|grep -q "nothing to commit, working tree clean"||git commit -am "自动生成navbar.md"
    - name: GitHub Push
      uses: ad-m/github-push-action@v0.6.0
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: gh-pages
        force: true